version: '3.7'
services:
  guacd:
    image: lprat/guacd:latest
    container_name: guacd
    restart: always
    environment:
      - GUACD_LOG_LEVEL=${GUACD_LOG_LEVEL}
      - TZ=${TZ}
    volumes:
      - ${LOCAL_PATH_RECORD}:/record
      - ${LOCAL_PATH_RDP}:/share_rdp
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 4822 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    #mem_reservation: '512m'
    #memswap_limit: '1g'
    #mem_limit: '1g'
    #cpuset: '1'
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://${SYSLOG_IP_SERVER}:514"
        tag: "docker_bastion_guacd_{{.ImageName}}_{{.Name}}"
  guacamole:
    image: lprat/guacamole-client:latest
    container_name: guacamole
    restart: always
#    volumes:
#      - ${LOCAL_PATH_SERVER_XML}:${GUEST_PATH_SERVER_XML}
    environment:
      - POSTGRES_USER=guacamole
      - POSTGRES_PASSWORD=guacamole
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_DATABASE=guacamole_db
      - TOTP_ISSUER=${TOTP_ISSUER}
      - TOTP_ENABLED=true
      - GUACD_HOSTNAME=guacd
      - API_SESSION_TIMEOUT=${API_SESSION_TIMEOUT}
    links:
      - guacd
      - postgres
      - chrome
    depends_on:
      guacd:
        condition: service_healthy
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -so /dev/null http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    #mem_reservation: '512m'
    #memswap_limit: '1g'
    #mem_limit: '1g'
    #cpuset: '1'
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://${SYSLOG_IP_SERVER}:514"
        tag: "docker_bastion_guacamole_{{.ImageName}}_{{.Name}}"
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=guacamole
      - POSTGRES_PASSWORD=guacamole
    restart: always
    volumes:
      - ${LOCAL_PATH_PGSQL}:/var/lib/postgresql/data
      - ./db:/db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U guacamole"]
      interval: 30s
      timeout: 5s
      retries: 5
    #mem_reservation: '512m'
    #memswap_limit: '1g'
    #mem_limit: '1g'
    #cpuset: '1'
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://${SYSLOG_IP_SERVER}:514"
        tag: "docker_bastion_postgres_{{.ImageName}}_{{.Name}}"
  chrome:
    image: lprat/chrome:latest
    restart: always
    #mem_reservation: '512m'
    #memswap_limit: '1g'
    #mem_limit: '1g'
    #cpuset: '1'
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://${SYSLOG_IP_SERVER}:514"
        tag: "docker_bastion_chrome_{{.ImageName}}_{{.Name}}"
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ${LOCAL_PATH_NGINX_CONF}:/etc/nginx/nginx.conf
      - ${LOCAL_PATH_CERT_NGINX}nginx.key:/etc/nginx/certs/cert.key
      - ${LOCAL_PATH_CERT_NGINX}nginx.pem:/etc/nginx/certs/cert.crt
      - ${LOCAL_PATH_CERT_NGINX}ca.pem:/etc/nginx/certs/bundle-client.pem
      - ${LOCAL_PATH_CERT_NGINX}dhparams.pem:/etc/nginx/certs/dhparams.pem
    restart: always
    links:
      - guacamole
    ports:
      - ${IP_BIND}443:443
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 5s
      retries: 5
    #mem_reservation: '512m'
    #memswap_limit: '1g'
    #mem_limit: '1g'GUACD_LOG_LEVEL
    #cpuset: '1'
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://${SYSLOG_IP_SERVER}:514"
        tag: "docker_bastion_nginx_{{.ImageName}}_{{.Name}}"
